### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by dkueng01** [tobedecided-at/tbd#20]
# David:
- [x] panel
- [x] icons
- [ ] wooden planks
> - [ ] kickitembutton
Was isch des? -DatNoHand

- [x] raster
- [x] Image that follows the mouse

# Gaben
EDIT: DatNoHand

- [x] Switch Items with mousewheel
- [x] Change _highlight_ color on selected hotbar slot
- [x] Move Items from Inv to Hotbar (load sprite)
- [ ] Function (Equip Item when selected)
- [x] Load Item images into UI
- [x] Open with Key
- [x] Mouse functions (left, right, middle)

**Comment by DatNoHand** [comment]
@dkueng01 guat
